# Uncomment the next line to define a global platform for your project 
# platform :ios, '9.0' 
 
target 'MORO' do 
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks 
  use_frameworks! 
  pod 'Alamofire' 
  pod 'FCUUID' 
  pod 'SnapKit' 
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'lottie-ios'
  # Pods for MORO 
 
end 
